var E_UNPAID_CONFIRM_COMM_AMT = DV.getFieldValue("E_UNPAID_CONFIRM_COMM_AMT");
var E_PAID_CONFIRM_COMM_AMT = DV.getFieldValue("E_PAID_CONFIRM_COMM_AMT");
var E_ORG_OUR_ENG_ADV_LC = DV.getFieldValue("E_ORG_OUR_ENG_ADV_LC");
if ((E_UNPAID_CONFIRM_COMM_AMT > 0 || E_PAID_CONFIRM_COMM_AMT > 0) && E_ORG_OUR_ENG_ADV_LC != "CONFIRMATION") {
    DV.appendField("EPLC_UPDATE_E_ORG_OUR_ENG_ADV_LC");
}
DV.appendField("EPLC_UPDATE_TTL_CONF_COMM");
DV.appendField("EPLC_UPDATE_UNPAID_CONF_COMM");