stp.setAutoProcess(true);
var sB6TAG = stp.getSWIFTTagValue("B6");
stp.writeLog("Birdie-B6:" + sB6TAG);
var s21TAG = stp.getSWIFTTagValue("21");
stp.writeLog("s21TAG:" + s21TAG);
var s20TAG = stp.getSWIFTTagValue("20");
stp.writeLog("s20TAG:" + s20TAG);
var s79TAG = stp.getSWIFTTagValue("79");
stp.writeLog("s79TAG:" + s79TAG);
var code = s79TAG.substr(1, 4);
var tag121 = stp.getSWIFTTagValue("121");
var year = stp.getSysBusiDate();
year = year.substr(3, 1);
var unitCode = stp.getBusiUnit().substr(2, 4);
var sRef = stp.SYS_getRefNo("PYMT_INW");
var ref = unitCode + year + sRef;
stp.writeLog("ref:" + ref);
stp.setMainRef(ref);
var trxdate = stp.getSysBusiDate();
stp.updateFieldValue("TRX_DT", trxdate);
stp.writeLog("trxdate:" + trxdate);
stp.updateFieldValue("UETR_GPI_121", tag121);
stp.updateFieldValue("SERVICE_TYPE_ID_GPI_111", "002");
stp.updateFieldValue("RCV_BK_SW_ADD", "TRCKCHZ0XXX");
stp.updateFieldValue("GSRP_STRC_TYPE", "RECV");
stp.updateFieldValue("RELATED_REF_NO", s21TAG);
stp.updateFieldValue("SENDER_REF", s20TAG);
stp.updateFieldValue("XN99_NARRATIVE_79", s79TAG);
stp.updateFieldValue("GSRP_STRC_CODE", code);
//var return_code='/PDCR/RQDA';
//var BOJSBIC='BOJSCNB0XXX';
//stp.updateFieldValue("TEMP_CHAR31",return_code+"\r\n"+BOJSBIC);
stp.setEventTimes(0);