uri1=/BL6CEWeb/screen/SECindex.htm
uri2=/BL6CEWeb/SYS_index.htm
uri3=/BL6CEWeb/Images/CSlogo.gif
uri4=/BL6CEWeb/theme/Standard.css
uri5=/BL6CEWeb/Images/Logon_button_normal.gif
uri6=/BL6CEWeb/Images/Logon_button_hover.gif
uri7=/BL6CEWeb/screen/WBindex.htm
uri8=/BL6CEWeb/SYS_JS/SYS_Common.js
uri9=/BL6CEWeb/Images/main_header.gif
uri10=/BL6CEWeb/Images/login_box.png
uri11=/BL6CEWeb/servlets/WSTrxManager
uri12=/BL6CEWeb/servlets/PasswordManager
uri13=/BL6CEWeb/screen/SYS_Forgot_Password.jsp
uri14=/BL6CEWeb/theme/welcome_general.css
uri15=/BL6CEWeb/JS/SYS_Forgot_Password.js
uri16=/BL6CEWeb/SYS_JS/jQuery/jquery.min.js
uri17=/BL6CEWeb/Plugins/autocomplete/jquery.autocomplete.css
uri20=/BL6CEWeb/theme/DataType.css
uri21=/BL6CEWeb/Plugins/autocomplete/jquery.autocomplete.js
uri22=/BL6CEWeb/SYS_JS/SYS_CrossBrowser.js
uri23=/BL6CEWeb/JS/CrossBrowser.js
uri24=/BL6CEWeb/SYS_JS/SYS_ActionFunc_CAL.js
uri25=/BL6CEWeb/SYS_JS/SYS_BaseFunc_CAL.js
uri26=/BL6CEWeb/SYS_JS/SYS_TranPage.js
uri27=/BL6CEWeb/SYS_JS/SYS_DealButton.js
uri28=/BL6CEWeb/SYS_JS/SYS_Pagination.js
uri29=/BL6CEWeb/SYS_JS/SYS_inbox.js
uri30=/BL6CEWeb/SYS_JS/SYS_menu_event.js
uri31=/BL6CEWeb/SYS_JS/SYS_Ajax.js
uri32=/BL6CEWeb/SYS_JS/SYS_AMTFormat.js
uri33=/BL6CEWeb/SYS_JS/SYS_DateFormat.js
uri34=/BL6CEWeb/SYS_JS/SYS_MD5Encrypt.js
uri35=/BL6CEWeb/SYS_JS/SYS_DataStructure.js
uri36=/BL6CEWeb/SYS_JS/SYS_XMLManager.js
uri37=/BL6CEWeb/SYS_JS/SYS_ErrHandle.js
uri38=/BL6CEWeb/widgets/framework/scripts/CSWidget.js
uri39=/BL6CEWeb/JS/Calendar.js
uri40=/BL6CEWeb/JS/Validation.js
uri41=/BL6CEWeb/JS/BaseFunc.js
uri42=/BL6CEWeb/JS/MainMenu.js
uri43=/BL6CEWeb/JS/Buttons.js
uri45=/BL6CEWeb/Plugins/jQueryUI/jquery-ui.min.js
uri46=/BL6CEWeb/Plugins/jQueryUI/jquery-ui.min.css
uri47=/BL6CEWeb/SYS_JS/browser.js
uri48=/BL6CEWeb/theme/DataType.css
uri49=/BL6CEWeb/widgets/framework/scripts/CSWidget.js
uri50=/BL6CEWeb/Images/default/form/icon-error.gif
uri51=/BL6CEWeb/theme/Calendar.css
uri52=/BL6CEWeb/Images/default/dd/drop-yes.gif
uri53=/BL6CEWeb/logout.do
uri54=/BL6CEWeb/JS/rsaencrypt/Publickey.js
uri55=/BL6CEWeb/JS/rsaencrypt/jsencrypt.min.js
uri56=/BL6CEWeb/servlets/RunBatchManager
uri57=/BL6CEWeb/servlets/WSSEmailLink
uri58=/BL6CEWeb/Images/simple2_h2.png
uri59=/BL6CEWeb/v1/message-api-receiver/stp/agreement
uri60=/BL6CEWeb/v1/message-api-receiver/stp/sbr
uri61=/BL6CEWeb/v1/message-api-receiver/stp/invoice
uri62=/BL6CEWeb/v1/message-api-receiver/stp/PO
uri63=/BL6CEWeb/v1/message-api-receiver/ping/hello
uri64=/BL6CEWeb/theme/Standard-customize.css
uri65=/BL6CEWeb/Images/navi_bg.png
uri66=/BL6CEWeb/Images/login_box2.png
uri67=/BL6CEWeb/JS/rsaencrypt/Publickey.js
uri68=/BL6CEWeb/JS/rsaencrypt/jsencrypt.min.js
uri69=/BL6CEWeb/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf
uri70=/BL6CEWeb/Images/header_bg4.jpg
uri71=/BL6CEWeb/Images/default/form/icon-error.gif
uri72=/BL6CEWeb/CS.ico
uri73=/favicon.ico
uri74=/BL6CEWeb/screen/loginfailPage.jsp
uri75=/BL6CEWeb/servlets/ClientMessageDealer
uri76=/BL6CEWeb/Images/bg.jpg
uri78=/BL6CEWeb/counterparty.html
uri79=/BL6CEWeb/servlets/CounterpartyInit
uri80=/BL6CEWeb/counterparty_error.html
sessionSSOFlag=isSSOContextFlag
uri81=/BL6CEWeb/rest/ping
uri82=/BL6CEWeb/rest/ce/ping
uri83=/BL6CEWeb/rest/ee/scfData
uri84=/BL6CEWeb/message-api-receiver/stp/agreement
uri85=/BL6CEWeb/message-api-receiver/stp/sbr
uri86=/BL6CEWeb/message-api-receiver/stp/invoice
uri87=/BL6CEWeb/message-api-receiver/stp/PO
uri88=/BL6CEWeb/message-api-receiver/ping/hello
uri89=/BL6CEWeb/servlets/TestingWgServlet
uri91=/BL6CEWeb/v1/openapi/calendar-event/event-lis
uri93=/BL6CEWeb/rest/ee/ping
uri94=/BL6CEWeb/getPrefillData
uri95=/BL6CEWeb/updateRejectStatus
uri96=/BL6CEWeb/rest/ee/enterprise/enquiry/v1/eq-acc-cif
uri97=/BL6CEWeb/servlets/WidgestServlet2
uri98=/BL6CEWeb/servlets/TestingServlet
uri99=/BL6CEWeb/TestingServlet