NFLoadBalancerPingInterval=10
server.status.startuptostarted=true
NFLoadBalancerRuleClassName=com.netflix.loadbalancer.WeightedResponseTimeRule
log.ClassName=com.cs.eximap.log.EELog
ServerListLoader.className=com.cs.cluster.EEServerListLoader
