stp.writeLog("********************");
stp.setAutoProcess(true);
stp.setEdiRule("InEDI07");

stp.updateFieldValue("FA_BUSI_STATUS", 'CAA');
stp.updateFieldValue("FA_BUSI_TYPE", 'IF');
stp.writeLog("@@@@@@@@@@@");
var CurrntStatus = "CCA";
var selId = stp.getXMLNodeValue("SellerNr", "MSG07.Seller", ".");
var buyId = stp.getXMLNodeValue("BuyerNr", "MSG07.Buyer", ".");
var expFactor = stp.getXMLNodeValue("FactorCode", "MSG07.EF", ".");
var lmtccy = stp.getXMLNodeValue("Currency", "MSG07.CurrentCreditCoverDetails", ".");
stp.updateFieldValue("FA_SEL_EDI_ID", selId);
stp.updateFieldValue("FA_BUYER_EDI_ID", buyId);
selId = selId.toUpperCase();
buyId = buyId.toUpperCase();
stp.updateFieldValue("FA_EF_ID", expFactor);
stp.writeLog("FA_EF_ID=" + expFactor);
var fld_list = stp.addFieldList(null, "C_MAIN_REF");
stp.writeLog("@@@@@@@@@@@@@@@@@@6666666666666666666");
var sql_condition = stp.addSQLCondition(null, "upper(FA_SEL_EDI_ID)", selId);
var sql_condition = stp.addSQLCondition(sql_condition, "upper(FA_BUYER_EDI_ID)", buyId);
var sql_condition = stp.addSQLCondition(sql_condition, "FA_EF_ID", expFactor);
var sql_condition = stp.addSQLCondition(sql_condition, "FA_LMT_CCY", lmtccy);
var sql_condition = stp.addSQLCondition(sql_condition, "FA_BUSI_TYPE", 'IF');
var sql_condition = stp.addSQLCondition(sql_condition, "CURRNT_STATUS", CurrntStatus);
var result = stp.executeQuery("FADA_MASTER", fld_list, sql_condition);
var mainRef = stp.getDBFieldValue(result, "C_MAIN_REF");
stp.writeLog("C_MAIN_REF=" + mainRef);
stp.updateFieldValue("C_MAIN_REF", mainRef);
stp.setEventTimesFromTable("FADA_MASTER");
stp.writeLog("%%%%%%%%%%%%");

var pre = 'IF';
var UnitCode = stp.getBusiUnit();
var year = stp.getSysBusiDate();
var month = stp.getSysBusiDate();
stp.updateFieldValue("TRX_DT", year);
year = year.substr(2, 2);
month = month.substr(5, 2);
var sub = 'CAA';
var ref = stp.SYS_getRefNo("IF_REVI_REQ");
var caaref = pre + UnitCode + year + month + ref + sub;
stp.writeLog("FA_CAA_REF=" + caaref);
stp.updateFieldValue("FA_CAA_REF", caaref);
stp.writeLog("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$end");