stp.setAutoProcess(true);
stp.writeLog("============ReceiveFinReqFromCE====start============");
stp.setGapiRule("BKTS_ABLF_001_ReqFin");

var pre = 'ABLF';
var UnitCode = stp.getBusiUnit();
var date = stp.getSysBusiDate();
year = date.substr(2, 2);
month = date.substr(5, 2);
var sub = 'LOAN';
var ref = stp.SYS_getRefNo("ABLF_LOAN");
var loanref = pre + UnitCode + year + ref + sub;
stp.updateFieldValue("FA_LOAN_ID", loanref);
stp.updateFieldValue("TRX_DT", date);
stp.updateFieldValue("FA_LOAN_STATUS", 'APPL');
stp.writeLog("---------------FA_LOAN_ID=" + loanref);

var MainRef = stp.getXMLNodeValue("CntrRef");
var ApplId = stp.getXMLNodeValue("ApplId");
var LoanCCY = stp.getXMLNodeValue("LoanCCY");
var ReqLoanAmt = stp.getXMLNodeValue("ReqLoanAmt");
var LoanDueDt = stp.getXMLNodeValue("LoanDueDt");
stp.writeLog("FA_CNTR_REF=" + MainRef);
var vFieldList = stp.addFieldList(null, "FA_CUST_NM");
vFieldList = stp.addFieldList(vFieldList, "FA_LMT_CCY");
vFieldList = stp.addFieldList(vFieldList, "FA_LMT_AMT");
vFieldList = stp.addFieldList(vFieldList, "FA_LMT_VAL_DT");
vFieldList = stp.addFieldList(vFieldList, "FA_LMT_DUE_DT");
var vCondition = stp.addSQLCondition(null, "C_MAIN_REF", MainRef);
var vResult = stp.executeQuery("EXIMTRX.ABLF_MASTER", vFieldList, vCondition);
var FA_CUST_NM = stp.getDBFieldValue(vResult, "FA_CUST_NM");
var FA_LMT_CCY = stp.getDBFieldValue(vResult, "FA_LMT_CCY");
var FA_LMT_AMT = stp.getDBFieldValue(vResult, "FA_LMT_AMT");
var FA_LMT_VAL_DT = stp.getDBFieldValue(vResult, "FA_LMT_VAL_DT");
var FA_LMT_DUE_DT = stp.getDBFieldValue(vResult, "FA_LMT_DUE_DT");
stp.updateFieldValue("C_MAIN_REF", MainRef);
stp.updateFieldValue("FA_LOAN_CCY", LoanCCY);
stp.updateFieldValue("FA_TTL_LOAN_AMT", ReqLoanAmt);
stp.updateFieldValue("FA_LOAN_DUE_DT", LoanDueDt);
stp.updateFieldValue("FA_CNTR_REF", MainRef);
stp.updateFieldValue("FA_CUST_ID", ApplId);
stp.updateFieldValue("FA_CUST_NM", FA_CUST_NM);
stp.updateFieldValue("FA_LMT_CCY", FA_LMT_CCY);
stp.updateFieldValue("FA_LMT_AMT", FA_LMT_AMT);
stp.updateFieldValue("FA_LMT_VAL_DT", FA_LMT_VAL_DT);
stp.updateFieldValue("FA_LMT_DUE_DT", FA_LMT_DUE_DT);

var RegNo = stp.getXMLNodeValue("RegRefNo");
stp.writeLog("REG_NO=" + RegNo);
stp.updateFieldValue("REG_NO", RegNo);
var vFieldList = stp.addFieldList(null, "REG_INSPEC_ID");
vFieldList = stp.addFieldList(vFieldList, "REG_INSPEC_NM");
var vCondition = stp.addSQLCondition(null, "REG_NO", RegNo);
var vResult = stp.executeQuery("EXIMTRX.ABLF_EM_REG", vFieldList, vCondition);
var REG_INSPEC_ID = stp.getDBFieldValue(vResult, "REG_INSPEC_ID");
var REG_INSPEC_NM = stp.getDBFieldValue(vResult, "REG_INSPEC_NM");
stp.updateFieldValue("REG_INSPEC_ID", REG_INSPEC_ID);
stp.updateFieldValue("REG_INSPEC_NM", REG_INSPEC_NM);

stp.writeLog("============ReceiveFinReqFromCE====END============");