# 0: table name; 1. column name; 2. column type
alter_col_add=ALTER TABLE {0} ADD {1} {2};
alter_col_add.db2=ALTER TABLE {0} ADD COLUMN {1} {2};
alter_col_add.oracle=ALTER TABLE {0} ADD ("{1}" {2})

# DB2: not suppor for 8.1 or earlier
# 0: table name; 1. column name; 
alter_col_drop=ALTER TABLE {0} DROP COLUMN {1};
alter_col_drop.db2=ALTER TABLE {0} DROP ({1} {2});
alter_col_drop.oracle=ALTER TABLE "{0}" DROP ("{1}") CASCADE CONSTRAINTS
#alter_col_drop.mysql=ALTER TABLE {0} DROP {1} {2};

# DB2: only for string and number
# 0: table name; 1. column name; 2. column type
alter_col_modify=ALTER TABLE {0} MODIFY {1} {2};
alter_col_modify.db2=ALTER TABLE {0} ALTER {1} SET DATA TYPE {2};
alter_col_modify.oracle=ALTER TABLE {0} MODIFY {1} {2};
alter_col_modify.mssql=ALTER TABLE {0} ALTER COLUMN {1} {2};

# DB2: not suppor for 8.1 or earlier, 8.2 use sp
# 0: table name; 1. old column name; 2. new column name; 3. new column type
alter_col_rename=
alter_col_rename.oracle=ALTER TABLE "{0}" RENAME COLUMN "{1}" TO "{2}"
alter_col_rename.mssql=EXEC sp_rename '{0}.{1}', '{2}', 'COLUMN';
alter_col_rename.mysql=ALTER TABLE {0} CHANGE {1} {2} {3};

show_tables=
show_tables.mysql=select TABLE_NAME from information_schema.tables where TABLE_TYPE=''BASE TABLE'' AND TABLE_SCHEMA=''{0}'';
#show tables;
show_tables.sqlite=.tables;