# This file only store jdbc information, other misc has move to sysconf.properties file.
# Only one meta db (must has), one security db, one standing data db, one ba db,
# 1~n trx db, 1~n web db, base on entity setting.
# here only setting default trx db. if other db not defined, use meta db.

# meta DB connection pool type: c3p0(default), jndi, dbcp, druid 
meta.jdbc.dbcp=druid

# Samples:
# Oracle
#meta.jdbc.driverClassName=com.ibm.db2.jcc.DB2Driver
#meta.jdbc.url=jdbc:db2://10.39.105.232:50000/TWGTSDB:currentSchema=ESPSCH;
#meta.jdbc.username=EXIMTRX
#meta.jdbc.password=EXIMTRX

#meta.jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#meta.jdbc.url=jdbc:oracle:thin:@10.39.103.157:1521:TSUTEST
#meta.jdbc.username=esp
#meta.jdbc.password=esp
#meta.jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#meta.jdbc.url=jdbc:oracle:thin:@10.39.104.39:30022/EEPDB
#meta.jdbc.username=EXIMTRX
#meta.jdbc.password=EXIMTRX

#meta.jdbc.driverClassName=net.sourceforge.jtds.jdbc.Driver
#meta.jdbc.url=jdbc:jtds:sqlserver://10.39.104.131:1433/ESP
#meta.jdbc.username=esp
#meta.jdbc.password=esp

#meta.jdbc.jndi=java:comp/env/jdbc/ESPDS
#meta.jdbc.driverClassName=org.mariadb.jdbc.Driver
meta.jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
meta.jdbc.url=jdbc:oracle:thin:@EEDB:1521/EEPDB
meta.jdbc.username=EXIMTRX
meta.jdbc.password=EXIMTRX
#meta.jdbc.url=jdbc:mysql://10.39.107.57/ESPDEMO?useInformationSchema=true
#meta.jdbc.username=qdog
#meta.jdbc.password=qdog

#meta.jdbc.url=jdbc:mysql://eedocker:28001/ESPDEMO?useInformationSchema=true
#meta.jdbc.username=espdemo
#meta.jdbc.password=espdemo
#meta.jdbc.password={DES}0xzu8rtVnpI7LmHh0i1yZA==
#meta.jdbc.schema=ESPDEMO.

# MySQL
#meta.jdbc.driverClassName=com.mysql.jdbc.Driver
#meta.jdbc.url=jdbc:mysql://<SERVER-URL>:3306/<SID>


#meta.jdbc.jndi=java:comp/env/jdbc/ESPDS
#meta.jdbc.driverClassName=com.ibm.db2.jcc.DB2Driver
#meta.jdbc.url=jdbc:db2://10.39.103.100:50000/GTSDB:currentSchema=EXIMTRX;
#meta.jdbc.username=eximtrx
#meta.jdbc.password=eximtrx

#meta.jdbc.driverClassName=SQLite.JDBCDriver
#meta.jdbc.url=jdbc:sqlite:/${esp.home}/meta/esp_demo.db


#jdbc.url=jdbc:mysql://10.102.13.183:3306/spdbwbi  tjqs  q_pacs
#meta.jdbc.url=jdbc:mysql://10.102.13.6:3306/qdog
#meta.jdbc.username=smms
#meta.jdbc.password=smms
meta.jdbc.prefix=
meta.jdbc.conn.max=20
meta.jdbc.conn.checkidle=900
meta.jdbc.conn.checksql=SELECT COUNT(*) FROM SYSM_SEQ_NUM

# For baseline payment demo, 201206 
#meta.jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#meta.jdbc.url=jdbc:oracle:thin:@10.39.105.90:1521:blrdb
#meta.jdbc.username=smms
#meta.jdbc.password=smms


#meta.jdbc.url=jdbc:mysql://127.0.0.1:3306/qdog_dragon

#jdbc.driverClassName=com.sybase.jdbc2.jdbc.SybDriver
#jdbc.url=jdbc:sybase:Tds:10.102.14.109:5000/spdbwbi
#hibernate.dialect=org.hibernate.dialect.SybaseDialect

# Property that determines the Hibernate dialect
#sec.jdbc.prefix=org.hibernate.dialect.MySQLDialect
#sec.jdbc.driverClassName=com.mysql.jdbc.Driver
#sec.jdbc.url=jdbc:mysql://127.0.0.1:3306/qsg
#sec.jdbc.username=root
#sec.jdbc.password=db2admin
#sec.jdbc.url=jdbc:mysql://10.102.12.196/qdog
#sec.jdbc.username=qdog
#sec.jdbc.password=qdog
#sec.jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#sec.jdbc.url=jdbc:oracle:thin:@rhel4svr:1521:SMMS

#ba.jdbc.prefix=eximq.
#ba.jdbc.driverClassName=com.mysql.jdbc.Driver
#jdbc.url=jdbc:mysql://10.102.13.183:3306/spdbwbi
#meta.jdbc.url=jdbc:mysql://10.102.13.6:3306/qdog
#meta.jdbc.username=qdog
#meta.jdbc.password=qdog
#ba.jdbc.url=jdbc:mysql://127.0.0.1/qdog
#ba.jdbc.username=qdog
#ba.jdbc.password=qdog
#ba.jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#ba.jdbc.url=jdbc:oracle:thin:@rhel4svr:1521:SMMS

# For generate PO mapping, it is typical transaction database.
#trx.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#trx.jdbc.driverClassName=com.mysql.jdbc.Driver
#trx.jdbc.url=jdbc:mysql://127.0.0.1:3306/qdog_dragon
#trx.jdbc.username=root
#trx.jdbc.password=db2admin
#trx.jdbc.url=jdbc:mysql://127.0.0.1/q_pacs
#trx.jdbc.username=smms
#trx.jdbc.password=qdog
#trx.jdbc.conn.max=30
#trx.jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#trx.jdbc.url=jdbc:oracle:thin:@dbsvr:1521:SMMS

#sec.jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#sec.jdbc.url=jdbc:oracle:thin:@10.39.105.90:1521:blrdb
#sec.jdbc.username=eximtrx
#sec.jdbc.password=eximtrx

#web.jdbc.driverClassName=net.sourceforge.jtds.jdbc.Driver
#web.jdbc.url=jdbc:jtds:sqlserver://10.39.104.131:1433/SMMS
#web.jdbc.username=smms
#web.jdbc.password=smms

#web.jdbc.driverClassName=org.mariadb.jdbc.Driver
#web.jdbc.url=jdbc:mysql://127.0.0.1/EXIMSYS
#web.jdbc.username=eximtrx
#web.jdbc.password=qeximtrx

#sec.jdbc.driverClassName=com.ibm.db2.jcc.DB2Driver
#sec.jdbc.url=jdbc:db2://10.39.105.232:50000/TWGTSDB:currentSchema=ESPSCH;
##sec.jdbc.url=jdbc:db2://10.39.103.100:50000/GTSDB:currentSchema=EXIMSYS;
#sec.jdbc.username=EXIMTRX
#sec.jdbc.password=EXIMTRX
# user=MyUserName;password=*****;
#sec.jdbc.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#sec.jdbc.url=jdbc:sqlserver://10.39.107.130:1433;databaseName=V4TRAN;
#sec.jdbc.driverClassName=net.sourceforge.jtds.jdbc.Driver
#sec.jdbc.url=jdbc:jtds:sqlserver://10.39.107.130:1433/V4TRAN
#sec.jdbc.username=sa
#sec.jdbc.password=Pa55w0rd

#___.dbcp=druid
#___.driverClassName=oracle.jdbc.driver.OracleDriver
#___.url=jdbc:oracle:thin:@eedocker:20012/BLDB
#___.username=EXIMTRX
#___.password=EXIMTRX
#___.driverClassName=org.mariadb.jdbc.Driver
#___.url=jdbc:mysql://10.39.107.57/ESPDEMO?useInformationSchema=true
#___.username=qdog
#___.password=qdog
