# this file config the exception of match rule for ESUN.
# it is better use javascript to descript the logic, but time is a issue.
# so still many rules is hard code in java source. see MtFxComparator.java.

# add 20210901 _s
# For tag 87J /NAME/xxx format, if the name match the ourname, we try to convert name to BIC setting in ourbic
# For ourbic, Singapore need set to ESUNSGSGXXX , HongKong need set to ESUNHKHHXXX
ourname=^E(\s|\.)*SUN\s*COMMERCIAL\s*BANK(.)*
ourbic=ESUNTWTPXXX
# add 20210901 _e

# first 8 bit match
mt300.rule.party_b=BBVAESMMFXD

# nine netting 57A, skip check 57
mt300.rule.57a_b1=BARCGB5G
mt300.rule.57a_b1.exp.AUD.WPACAU2F=WPACAU2S|WPACAU2F

# nine netting 57A_b2, skip check 57
mt300.rule.57a_b2=BARCGB5G
mt300.rule.57a_b2.exp.TWD.WPACAU2F=CRESCHZZ

# 320 82A bit match
mt320.rule.party_b=UWCBTWTP800
# MM Over Account, skip check 15C 15D 57A,57D
mt320.rule.57a.exp=OVER ACCOUNT


# 306
# first 8 bit match
mt306.rule.party_b=BBVAESMMFXD


# audit mode: all-matched and mismatched; mismatch-; none-not write into db, default.
match.audit.mode=none 
# 7 field, runtime param is C_LOG_ID, C_SEVERITY, C_MAIN_REF(Ixxx F20), C_ERR_INFO, D_BU_DATE, BOOK_ID, MSG_ID
# example: {"LOG2014060707", "ERROR", "I300.F20","Mistach field: ....\nMsg:...", '20140705', '','' }
match.audit.sql=INSERT INTO EXIMSYS.TRX_SYS_ERR_LOG (C_LOG_ID,C_CLASS_NAME,C_SEVERITY,C_MAIN_REF,C_ERR_INFO,D_BU_DATE, C_SESSION_ID,C_FUNC_NAME) VALUES (?,'MATCH',?,?,?,?,?,?)

F31G.JPTO=TOKYO
F31G.USNY=NEW YORK
F31G.TWTA=TAIPEI
F31G.CNBE=BEIJING 
F31G.HKHK=HONGKONG
F31G.AUSY=SYDNEY
F31G.KRSE=SEOUL
F31G.DEFR=FRANKFURT
F31G.TKO=TOKYO