# security key, security.json will be used if not set.
deskey=1@3$5^7*9)1@3$5^
# default date time display format
fmt.datetime=yyyyMMdd hhmmss
# depeated, for SCFU
sys.tmp.folder=/tmp
# depeated, java and js code gen out folder
gen.cls.root=${esp.home}/codegen
genjs.cls.root=${esp.home}/cls
# see ScriptRunner.java for some AIX WAS has compiler error.
# also for workbench gen code and compile
gen.cls.cp=${esp.home}/codegen:${esp.home}/lib/qdog.biz.jar:${esp.home}/lib/qdog.core.jar:${esp.home}/lib/org.json.jar

# thread pool size
thread.pool.size=100
thread.init.size=10
thread.asyncpool.size=100
thread.queue.size=1
thread.asynqueue.size=100
# For cache manager
cache.size=100
page.size=100

# folder for MT mfvr js, MX mxvr js.
swift.mfvr=${esp.home}/swift/js
# SWIFT output format: DOSPCC / RJE / NULL, for CSX folder mode only
swift.format=RJE
# allow SWIFT message add missed tags later, so ESP should reduce the message length limit.
#  syntax: tag:len  e.g: 108: 22, 119: 20, MDG: 36
# swift.len.tags=AA:44

# 98529 ack nack will store all isn.
# fin.ack.isn=true
# mode: 0 - POJO, all in one; 1 - web, ejb home call; 2 - web, ejb remote call; 3 - ap;
#mode.webap=0
#mode.pwd={DES}0xzu8rtVnpI7LmHh0i1yZA==


# validate the external code list in MX XSD.
swift.val.extcode = true
# check incoming message like O103, default is true
swift.val.oxxx=true

esp.console=CFB527A7EDB6B64B7B649D6760F512D516D9898DA1391CB46ED073DA7B34841B
#auth.adapter=com.cs.qdog.security.DemoAuthenticator
#auth.adapter=com.cs.qdog.security.SecurityDBAuthenticator

# 74386, times to sync ram cache with DB in RestapiProtocol, default is 2000
restapi.loop=2000

#ESP_HOST=http://10.39.107.37:9080/ESP/rs
ESP_HOST=http://10.39.104.106:30100/ESP/rs
#ESP_HOST=http://127.0.0.1:8087/ESP/rs
# ESP_HOST=http://10.39.107.57:9080/esp/rs
#ESP_HOST=http://10.39.107.57:8060/esp.wsapi/rs

# ------  properties setting via utility ------
# startup listener, true or false
startup.thread=true

# For duplicate message check using FIN mode, default is full text content, all means use FIN, other use the list of extenal system name
# fin.mode.src=REST,SAA
# fin.mode.src=all
# fin.mode.src=off
fin.mode.src=full

# For SWIFT version
swift.fin.version=2023

# check bic, ccy, country against database. Default is 'false'.
# 'false' means not check.
# 'true' means use ee's datasource and bic_mapping.json
# 'ixxx' means only check Ixxx message, skip Oxxx check.
swift.val.bic=true

# indicate MX app header  BizMsgIdr value from, default is 'f20', '108' will use tag 108 from block 3.
swift.mx.app.msgid=f20

# keep the raw info or truncate it when converting MX to MT. default is mt, will truncate. mx will keep raw info.
swift.mx.truncate=mt

# check RMA in message base on MT, sender bic and receiver bic, default is false
#swift.val.rma=true

# mt2mx validation mode: default is use mt, other: none, mx, cvt, mtmx
mt2mx.val=mt

# check token method: esp - use esp internal; csauth - use cscloud auth
auth.token=esp
# check user method: esp - use esp internal; csx - use csx db; ee - use ee db
auth.user=esp

