#
# Copyright (c) 2016. China Systems Nanjing Corp.
#

ecm.adapter=cs.cs.esp.tradedoc.impl.LogicalDocWsdl

# Folder name template
fd.tmpl=${C_UNIT_CODE}/${C_MODULE}/${C_MAIN_REF}

#################
# com.cs.esp.tradedoc.impl.LocalFs
# Local file system properties
#################
fs.folder = /tmp

#################
# com.cs.esp.tradedoc.impl.LogicalDocWsdl
# LogicalDoc 7.4 WSDL mode properties
# please modify the IP address in $esp_home/wsdl/logicaldoc.*.wsdl
#################

default_tmpl_id=3440640
root_folder_id=4
root_folder_path=/Default

username=admin
password=admin

#################
# com.cs.esp.tradedoc.impl.LogicalDocRestV7
# LogicalDoc 7.4 REST mode properties
#################

svr_base=http://10.39.107.57:8600/logicaldoc
soap_base=http://10.39.107.57:8600/logicaldoc/services/Document?wsdl
download_url=http://10.39.107.57:8600/logicaldoc/download?sid=$SID&docId=$DOC_ID

auth_url=http://10.39.107.57:8600/logicaldoc/services/Auth
folder_url=http://10.39.107.57:8600/logicaldoc/services/Folder
doc_url=http://10.39.107.57:8600/logicaldoc/services/Document
search_url=http://10.39.107.57:8600/logicaldoc/services/Search

rest_auth=http://10.39.107.57:8600/logicaldoc/services/rest/auth
rest_doc=http://10.39.107.57:8600/logicaldoc/services/rest/document
rest_folder=http://10.39.107.57:8600/logicaldoc/services/rest/folder

rest_comment=http://10.39.107.57:8600/logicaldoc/services/mobile/comments\
#  Get doc's comments:  /getcomments/$SID/$DOC_ID
#  add comments to doc: addcomment/$SID/$DOC_ID

####### END ##########