# warning: donot use char: \/?:*<>"|, because id may use as file name.
sys_uuid=[uuid]
sys_num=[yyMMdd]{3}
sys_ref10=[yyMMdd]{2}
sys_ref=[yyyyMMdd]{6}
# bolero_id={4}
# meta may use 
sysm_bod_field=BZFD[yyMMdd]{5}
sysm_bod_bizcomp=BZCO[yyMMdd]{5}
sysm_bod_boflds=BOFD[yyMMdd]{5}
sysm_bod_keyrel=BOKR[yyMMdd]{5}
sysm_bod_prod=BZPD[yyMMdd]{5}
sysm_bod_bpobjs=BPFD[yyMMdd]{5}
sysm_bod_scrn=BOSC[yyMMdd]{5}
sysm_bod_state=BPST[yyMMdd]{5}
sysm_bod_step=BPSP[yyMMdd]{5}
sysm_bod_wkf=BPWF[yyMMdd]{5}
sysm_bst_state=WFST[yyMMdd]{5}
sysm_bst_step=WFSP[yyMMdd]{5}
sysm_gapi_lstn=LSTN[yyMMdd]{5}
sysm_gapi_ptcl=PTCL[yyMMdd]{5}
sysm_gapi_schema=GPSC[yyMMdd]{5}
sysm_gapi_xltrule=GPXL[yyMMdd]{5}
sysm_grp_node=BZND[yyMMdd]{5}
sysm_std_codelist=STCL[yyMMdd]{5}
sysm_std_coderule=STCR[yyMMdd]{5}
sysm_std_i18n=STIN[yyMMdd]{5}
sysm_std_refrule=STRF[yyMMdd]{5}
sysm_doctmpl_info=DCTP[yyMMdd]{5}
sysm_match_tmpl=M[yyMMdd]{5}
# trx table
#match_book=MTBK[yyMMdd]{5}
match_book=[yyyyMMdd]{3}-[HHmm]-[ss]
#match_book=20141029276-0313-10
syst_bst_inbox=WK[yyMMdd]{7}
syst_gapi_log=LG[yyMMdd]{7}
syst_audit_log=LG[yyMMdd]{7}
syst_doc_index=DC[yyMMdd]{7}
syst_event=EVT[yyMMdd]{6}
syst_swf_ssn=5666{6}
#
secu_entity=ET[yyMMdd]{6}
ee_ref=EP{5}BEDV
