# Properties file for prompt messages.
# table.ds
# table.sql
# if you donot want use cache, uncomment below
# _sys_cache=none

# meta: common
SYSM_GRP_NODE.sql=SELECT * FROM SYSM_GRP_NODE WHERE NODE_ID = ?
# meta: gapi
SYSM_GAPI_SCHEMA.sql=SELECT C_NAME, C_ID, C_DESC, C_TYPE,T_XML, C_BO FROM SYSM_GAPI_SCHEMA WHERE C_ID=?
SYSM_GAPI_XLTRULE.sql=SELECT C_NAME, C_ID, C_DESC,C_TYPE,T_XSL, SRC_ID,TGT_ID FROM SYSM_GAPI_XLTRULE WHERE C_ID=?
SYSM_GAPI_PTCL.sql=SELECT C_NAME,C_DESC,C_TYPE,T_CTX,IS_SYNC,C_CONVERTER,C_EXT_NAME,C_ID FROM SYSM_GAPI_PTCL WHERE C_ID = ?
SYSM_GAPI_LSTN.sql=SELECT C_NAME,C_PTCL,T_SCRIPT,I_INTERVAL,C_XLTRULE,C_MODE,C_TRIGER,C_TRIGER_TYPE,C_START_TIME, C_ID FROM SYSM_GAPI_LSTN WHERE C_ID = ?
# meta: BOD
SYSM_BOD_TYPE.sql=SELECT * FROM SYSM_BOD_TYPE WHERE I_ID=?
SYSM_BOD_FIELD.sql=SELECT * FROM SYSM_BOD_FIELD WHERE C_ID = ? 
SYSM_BOD_BIZCOMP.sql=SELECT * FROM SYSM_BOD_BIZCOMP WHERE C_ID=?
SYSM_BOD_BOFLDS.sql=SELECT * FROM SYSM_BOD_BOFLDS WHERE I_ID=?
SYSM_BOD_BORULE.sql=SELECT * FROM SYSM_BOD_BORULE WHERE C_ID=?
SYSM_BOD_KEYREL.sql=SELECT C_REF_BO, C_SELF_ELMS, C_REF_ELMS FROM SYSM_BOD_KEYREL WHERE C_BO_ID=? AND C_TYPE_KR='K' AND C_TYPE='P'
SYSM_BOD_PROD.sql=SELECT * FROM SYSM_BOD_PROD WHERE C_ID=?
SYSM_BOD_STEP.sql=SELECT C_ID, C_NAME, T_COMPS, T_ACTION, T_GAPI,C_PAGE_ID,C_PROD_ID FROM SYSM_BOD_STEP WHERE C_ID=?
# meta: transaction and workflow
SYSM_BOD_WKF.sql=SELECT C_NAME, C_PROD_ID, C_ID FROM SYSM_BOD_WKF WHERE C_ID=?
SYSM_BOD_SCRN.sql=SELECT C_NAME, C_ID, C_URL, T_COMPS,C_TYPE  FROM SYSM_BOD_SCRN WHERE C_ID=?
SYSM_BOD_STATE.sql=SELECT * FROM SYSM_BOD_STATE WHERE C_ID=?
# meta: parameter
SYSM_DOCTMPL_INFO.sql=SELECT C_NAME, C_ID, T_BODY FROM SYSM_DOCTMPL_INFO WHERE C_ID=?
SYSM_STD_CODERULE.sql=SELECT C_NAME, C_ID, C_TYPE FROM SYSM_STD_CODERULE WHERE C_ID=?
SYSM_STD_REFRULE.sql=SELECT C_NAME, C_ID  FROM SYSM_STD_REFRULE WHERE C_ID=?
SYSM_MATCH_TMPL.sql=SELECT * FROM SYSM_MATCH_TMPL WHERE C_ID=?

# standing data, should define ds: meta.jdbc (default) trx.jdbc sec.jdbc web.jdbc
STD_FACILITY.ds=trx.jdbc
STD_FACILITY.sql=SELECT MY_REFERENCE, FACILITY_NAME_ENG FROM STD_FACILITY WHERE MY_REFERENCE=?
STD_EXPOSURE_CATEGORY.ds=trx.jdbc
STD_EXPOSURE_CATEGORY.sql=SELECT RECORD_KEY, EXPOSURE_CATEGORY_ENG,ADVANCE_RATE FROM STD_EXPOSURE_CATEGORY WHERE RECORD_KEY=?
STD_COLLATERAL_CATEGORY.ds=trx.jdbc
STD_COLLATERAL_CATEGORY.sql=SELECT RECORD_KEY, COLLATERAL_CATEGORY_ENG,ADVANCE_RATE FROM STD_COLLATERAL_CATEGORY WHERE RECORD_KEY=?
STD_COMMODITY.ds=trx.jdbc
STD_COMMODITY.sql=SELECT COMMODITY_ID, PRODUCT_NAME FROM STD_COMMODITY WHERE COMMODITY_ID=?

STD_TOLERANCE.ds=trx.jdbc
STD_TOLERANCE.sql=SELECT MY_REFERENCE, BIC, CCY, AMOUNT FROM STD_TOLERANCE WHERE CCY=?

# BA data
# BA_TEMP.sql=SELECT TEMP_NAME,CCY_CODE,LEDG_CODE_1,LEDG_CODE_2,LEDG_CODE_3,LEDG_CODE_4,LEDG_CODE_5,CD_NUM, TEMP_ID  FROM BA_TEMP WHERE TEMP_ID=?
BA_TEMP.sql=SELECT * FROM BA_TEMP WHERE TEMP_ID=?
BA_TEMP_GR.sql=SELECT TEMP_GR_NAME, TEMP_GR_ID FROM BA_TEMP_GR WHERE TEMP_GR_ID=?
SYSM_BATP_DEF.sql=SELECT * FROM SYSM_BATP_DEF WHERE TMPL_ID=?
SYSM_BATG_DEF.sql=SELECT * FROM SYSM_BATG_DEF WHERE TPGR_ID=?
