# For the general syntax of property based configuration files see the
# documenation of org.apache.log4j.PropertyConfigurator.

# log4j.loggerFactory=com.cs.esp.esapi.Log4JLoggerFactory

# log4j.rootCategory=DEBUG, file, stdout,CHAINSAW_CLIENT
log4j.rootLogger=error, stdout

log4j.logger.HEARTBEAT=debug,heart
log4j.logger.org.json=debug,E
log4j.logger.com.cs.esp.db=debug,db
log4j.logger.ESPLOG=debug,E
log4j.logger.test.cs=debug

# stdout appender use for root.
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%5p %-d{HH:mm:ss,SSS} [%t] (%F:%L) %M() - %m%n

# rolling file appender
log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.Encoding=UTF-8
log4j.appender.file.File=${esp.home}/logs/smms_log4j.log
log4j.appender.file.MaxFileSize=1000KB
log4j.appender.file.MaxBackupIndex=3
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%-5p %-d{HH:mm:ss} [%t] (%F:%L) %M() - %m%n

# when ESP work within EE, please use following log setting.
#log4j.appender.file=com.cs.base.log.CSDailyRollingFileAppender
#log4j.appender.file.File=ESP.log
#log4j.appender.file.CSFile=ESP.log
#log4j.appender.file.Append=true
#log4j.appender.file.Encoding=UTF-8
#log4j.appender.file.layout=org.apache.log4j.PatternLayout
#log4j.appender.file.layout.ConversionPattern=%-5p %-d{HH:mm:ss} [%t] (%F:%L) %M() - %m%n


log4j.appender.heart=org.apache.log4j.RollingFileAppender
log4j.appender.heart.File=/tmp/heart.log
log4j.appender.heart.MaxFileSize=100KB
log4j.appender.heart.MaxBackupIndex=1
log4j.appender.heart.layout=org.apache.log4j.PatternLayout
log4j.appender.heart.encoding=UTF-8
log4j.appender.heart.layout.ConversionPattern=%-4r %d  %-5p [%t] (%x) - %m\n

# daily rolling file.
log4j.appender.E = org.apache.log4j.DailyRollingFileAppender
#log4j.appender.E.File = c:/temp/smms_error.log
log4j.appender.E.File=/tmp/smms_error.log
log4j.appender.E.Append = false
log4j.appender.E.Threshold = DEBUG
log4j.appender.E.layout = org.apache.log4j.PatternLayout
log4j.appender.E.layout.ConversionPattern=%-5p %-d{HH:mm:ss} [%t] (%F:%L) - %m%n

log4j.appender.db=org.apache.log4j.DailyRollingFileAppender
log4j.appender.db.File=/tmp/smms_db.log
log4j.appender.db.Append = false
log4j.appender.db.layout = org.apache.log4j.PatternLayout
log4j.appender.db.layout.ConversionPattern=%-5p %-d{HH:mm:ss} [%t] (%F:%L) - %m%n
