# Properties file for prompt messages.

E_LOAD_STEP_INFO=Cannot load step info: {0}
E_FIELD_NOT_FOUND=Cannot find field: {0}

T_RESP_OK=Response OK. 
E_INVALID_VALUE=Invaild field value, field [{0}], value [{1}] 
E_LOGIN=Invalid login user name, password or unit code, please try again. 
E_NO_USER = Login please.
E_NO_PERMISSION=You do not have permission to do this!
S00001   = Wrong user type to Login the system
S00002   = Wrong username or password or wrong user type to login
S00003   = unknow error when login
S00004   = sesison is timeout,please login
S00005   = Access to [#] is denied
S00006   = Can not find the owner of Step[#]
E_FTL001 = Freemarker generate error, message is: {0}
# Properties file for prompt messages.

E_SWIFT_VAL=SWIFT Validate error: {0}
E_BAD_LOGIN=Invalid login user name, password or unit code, please try again: {0}. 
ERR_INVALID_ID_OR_PWD=Invalid login id or password, please try again.
ERR_LOCKED_USER=This user is locked, please contact security administrator.
ERR_DISABLED_USER=This user is disabled, please contact security administrator.
ERR_IN_AUTH_QUEUE=Changes cannot be saved. Maybe it was edited by another administrator before, but the changes has not been authorized yet.

E10000=General Error
E10001=Cannot find file: {0}
E10050=SWIFT validate error: {0}
E10051=No SWIFT parameter file: {0}, {1}
E20010=Duplicate message
E20011=Convert message error. {0}
E20012=Send message error. {0}
E20022=Cannot send message to JMS Queue. QueueManager: {0} Queue: {1}.